language: erlang
otp_release:
  - 17.4
  - 18.2
services:
  - postgresql
before_script:
  - psql -c \"create role ffengine with login password 'ffengine'\"; -U postgres
  - psql -c \"create database ffengine owner ffengine;\" -U postgres
  - psql -c \"grant all on database ffengine to ffengine;\" -U postgres
  - echo \"localhost:5432:ffengine:ffengine:ffengine\" >> ~/.pgpass
  - chmod 0600 ~/.pgpass
  - psql -d ffengine -h localhost -U ffengine -f db/schema.sql
  - psql -d ffengine -h localhost -U ffengine -f db/functions.sql
script:
  - make tests

